avatar:
  img: /img/avatar.png
  effect: false # 头像会一直转圈


menu:
  Home: / || fas fa-home
  Archives: /archives/ || fas fa-archive
  # Tags: /tags/ || fas fa-tags
  # Categories: /categories/ || fas fa-folder-open
  # List||fas fa-list:
  Music: https://music.163.com/#/user/home?id=446315327 || fas fa-music
    # Movie: /movies/ || fas fa-video
  Link: /link/ || fas fa-link
  # About: /about/ || fas fa-heart

highlight_copy: true
highlight_shrink: false

copy:
  enable: true
  copyright:
    enable: false
    limit_count: 50
post_copyright:
  enable: false
  decode: false
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/


social:
  fab fa-github: https://github.com/cpdyj || Github
  fas fa-envelope: mailto:admin@iseki.space || Email

toc:
  enable: true
  number: true
  style_simple: true

related_post:
  enable: true
  limit: 6 # 显示推荐文章数目
  date_type: created # or created or updated 文章日期显示创建日或者更新日

anchor: true

# Displays outdated notice for a post (文章过期提醒)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 90 # When will it be shown
  position: top # position: top/bottom
  message_prev: It has been
  message_next: days since the last update, the content of the article may be outdated.

# Post edit
# Easily browse and edit blog source code online.
post_edit:
  enable: false
  # url: https://github.com/user-name/repo-name/edit/branch-name/subdirectory-name/
  # For example: https://github.com/jerryc127/butterfly.js.org/edit/main/source/
  url:

post_pagination: false

footer:
  owner:
    enable: true
    since: 2018

# custom_text: Hi, welcome to my <a href="https://butterfly.js.org/">blog</a>!

translate:
  enable: true
  # 默认按钮显示文字(网站是简体，应设置为'default: 繁')
  default: 简
  #网站默认语言，1: 繁体中文, 2: 简体中文
  defaultEncoding: 1
  #延迟时间,若不在前, 要设定延迟翻译时间, 如100表示100ms,默认为0
  translateDelay: 0
  #当文字是简体时，按钮显示的文字
  msgToTraditionalChinese: "繁"
  #当文字是繁体时，按钮显示的文字
  msgToSimplifiedChinese: "简"

# dark mode
darkmode:
  enable: true
  # dark mode和 light mode切换按钮
  button: true
  autoChangeMode: 1 # follow system

readmode: true

# Change font size
change_font_size: true

aside:
  enable: true
  hide: false
  button: true
  mobile: true # 手机页面（ 显示宽度 < 768px ）是否显示aside内容
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: false
	  icon: fab fa-github
    text: Github
    link: https://github.com/cpdyj/
  card_announcement:
    enable: true
    content: 公告？没啥可写的
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true

runtimeshow:
  enable: true
  publish_date: 2019/10/17 00:00:00

mathjax:
  enable: true
  # true 表示每一页都加载mathjax.js
  # false 需要时加载，须在使用的Markdown Front-matter 加上 mathjax: true
  per_page: true

# background: url(/img/topimg.jpg)
default_top_img: /img/topimg.jpg
index_img: /img/topimg.jpg
archive_img: /img/topimg.jpg
tag_img: /img/topimg.jpg
category_img: /img/topimg.jpg
disable_top_image: false

preloader: true

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

fancybox: true

css_prefix: true

Open_Graph_meta: true

# https://instant.page/
# prefetch (预加载)
instantpage: true

pangu:
  enable: false
  field: post # site/post

inject:
  head:
  	# - <link rel="stylesheet" href="/self.css">
  bottom:
  	# - <script src="xxxx"></script>

sharejs:
  enable: false

cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover: 
    - /img/randombg/1.png
    - /img/randombg/2.png
    - /img/randombg/3.png
    - /img/randombg/4.png
    - /img/randombg/5.png
    - /img/randombg/6.png
    - /img/randombg/7.png
    - /img/randombg/8.png
    - /img/randombg/9.png
    - /img/randombg/10.png

error_404:
  enable: true
  subtitle: "页面没有找到"
  background: 
