name: Build Blog Hexo
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          npm install -g pnpm 
          pnpm i
      - name: prepare
        run: |
          pwd
          git config --global user.name "My Github Action"
          git config --global user.email "no-reply@iseki.space"
      - name: hexo clean
        run: |
          pnpm hexo clean
      - name: generate
        run: |
          pnpm hexo g
      - name: prepare commit
        run: |
          mv docs /tmp
          git add .
          git stash
          git fetch origin website:website --depth 1
          git checkout website
          rm -rf docs
          mv /tmp/docs .
      - name: commit and push
        run: |
          git add .
          git commit -am "Auto generate on Github Action at `date`"
          git push origin website
